version: "3.9"

services:
  spark-master:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ../../data:/app/data

  spark-worker:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ../../data:/app/data
